In [ ]:
#pandas

In [1]:
import pandas as pd

In [2]:
help(pd)

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
#series-1d,dataframe-2d,panel-3d

In [4]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
a.ndim

1

In [11]:
#series
a=pd.Series([1,2,3,4,5],dtype="float")
a

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [7]:
a.ndim

1

In [8]:
a.shape

(5,)

In [9]:
a.size

5

In [12]:
a.dtype

dtype('float64')

In [16]:
b=pd.Series([10,20,"30",40,50],index=["A","B","C","D","E"])
b

A    10
B    20
C    30
D    40
E    50
dtype: object

In [17]:
#series creation by using an array
a=np.arange(2,51,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [18]:
s=pd.Series(a)
s

0      2
1      4
2      6
3      8
4     10
5     12
6     14
7     16
8     18
9     20
10    22
11    24
12    26
13    28
14    30
15    32
16    34
17    36
18    38
19    40
20    42
21    44
22    46
23    48
24    50
dtype: int64

In [ ]:
#head and tail

In [21]:
s.head()

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [23]:
s.tail()

20    42
21    44
22    46
23    48
24    50
dtype: int64

In [24]:
s.index

RangeIndex(start=0, stop=25, step=1)

In [25]:
s.values

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [26]:
s.sum()

np.int64(650)

In [27]:
s.mean()

np.float64(26.0)

In [29]:
s.sort_values(ascending=False)

24    50
23    48
22    46
21    44
20    42
19    40
18    38
17    36
16    34
15    32
14    30
13    28
12    26
11    24
10    22
9     20
8     18
7     16
6     14
5     12
4     10
3      8
2      6
1      4
0      2
dtype: int64

In [30]:
s[0]

np.int64(2)

In [31]:
s[1]

np.int64(4)

In [32]:
s[5:11]

5     12
6     14
7     16
8     18
9     20
10    22
dtype: int64

In [33]:
s[:]

0      2
1      4
2      6
3      8
4     10
5     12
6     14
7     16
8     18
9     20
10    22
11    24
12    26
13    28
14    30
15    32
16    34
17    36
18    38
19    40
20    42
21    44
22    46
23    48
24    50
dtype: int64

In [40]:
a=pd.Series([1,2,3])
b=pd.Series([4,5,6])

In [ ]:
#nan-not a number

In [39]:
x=a.add(b)
x

0    5.0
1    7.0
2    9.0
3    NaN
dtype: float64

In [36]:
x=a.subtract(b)
x

0   -3
1   -3
2   -3
dtype: int64

In [37]:
x=a.multiply(b)
x

0     4
1    10
2    18
dtype: int64

In [42]:
x=pd.concat([a,b],ignore_index=True)
x

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
#series creation using a dictionary

In [43]:
d={"id":100,"name":"sona","age":27,"location":"kochi"}
d

{'id': 100, 'name': 'sona', 'age': 27, 'location': 'kochi'}

In [47]:
a=pd.Series(d,index=["id","name"])
a

id       100
name    sona
dtype: object

In [48]:
a[1]

/tmp/ipython-input-240059899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  a[1]


'sona'

In [49]:
a["name"]

'sona'

In [ ]:
#dataframe

In [50]:
a=pd.Series([1,2,3,4])
a

0    1
1    2
2    3
3    4
dtype: int64

In [51]:
b=pd.DataFrame([1,2,3,4])
b

0
0  1
1  2
2  3
3  4

In [53]:
a.ndim
b.ndim

2

In [54]:
b.shape

(4, 1)

In [55]:
b.size

4

In [ ]:
#1.dataframe using nested list
#2.using dictionary of list
#using list of dictionaries

In [56]:
#1.
lst=[[101,"abhi",45],[102,"manuel",50],[103,"chandini",52]]
lst

[[101, 'abhi', 45], [102, 'manuel', 50], [103, 'chandini', 52]]

In [58]:
df=pd.DataFrame(lst,columns=["id","name","mark"])
df

id      name  mark
0  101      abhi    45
1  102    manuel    50
2  103  chandini    52

In [59]:
#2.
d={"id":[101,102,103],"name":["abhi","manuel","chandini"],"mark":[45,50,52]}
d

{'id': [101, 102, 103],
 'name': ['abhi', 'manuel', 'chandini'],
 'mark': [45, 50, 52]}

In [60]:
a=pd.DataFrame(d)
a

id      name  mark
0  101      abhi    45
1  102    manuel    50
2  103  chandini    52

In [65]:
#3.
lst=[{"id":101,"name":"abhi","mark":45},{"id":102,"name":"manuel","mark":50},{"id":103,"name":"chandini","mark":52}]
lst

[{'id': 101, 'name': 'abhi', 'mark': 45},
 {'id': 102, 'name': 'manuel', 'mark': 50},
 {'id': 103, 'name': 'chandini', 'mark': 52}]

In [66]:
a=pd.DataFrame(lst)
a

id      name  mark
0  101      abhi    45
1  102    manuel    50
2  103  chandini    52

In [69]:
a[["name","id"]]

name   id
0      abhi  101
1    manuel  102
2  chandini  103

In [71]:
#to add a new column to the dataframe
#dataframe[colname]=[values]
a["gender"]=["M","M","F"]
a

id      name  mark gender
0  101      abhi    45      M
1  102    manuel    50      M
2  103  chandini    52      F

In [72]:
#insert
a.insert(loc=2,column="age",value=[20,22,24])
a

id      name  age  mark gender
0  101      abhi   20    45      M
1  102    manuel   22    50      M
2  103  chandini   24    52      F

In [76]:
#deleting a column
a.drop(["mark"],axis=1,inplace=True)#colum,axis=0-row


In [77]:
a

id      name  age gender
0  101      abhi   20      M
1  102    manuel   22      M
2  103  chandini   24      F

In [81]:
a.head(1)

id  name  age gender
0  101  abhi   20      M

In [82]:
a.tail(1)

id      name  age gender
2  103  chandini   24      F

In [ ]:
#create a dataframe consist of name,age,job-and add details of 3 persons using
#1.nested list   2.dictionary of list    3.list of dictionaries
#add a new column "salary" at location 2

In [83]:
a.columns

Index(['id', 'name', 'age', 'gender'], dtype='object')

In [84]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      3 non-null      int64 
 1   name    3 non-null      object
 2   age     3 non-null      int64 
 3   gender  3 non-null      object
dtypes: int64(2), object(2)
memory usage: 228.0+ bytes


In [85]:
a.describe()

id   age
count    3.0   3.0
mean   102.0  22.0
std      1.0   2.0
min    101.0  20.0
25%    101.5  21.0
50%    102.0  22.0
75%    102.5  23.0
max    103.0  24.0